### ISSUE TITLE
BUG: Using WebexMeetings widget, Unable to add media WebexMeetingError

### ISSUE THREAD

**Issue by giospada** [webex/widgets#175]
I'm trying to use webex/widget (for meeting), i use react, webpack( version 4, because the version 5 give me too much error) and @webex/widgets, i'm trying with all dependency update but still getting this error.

I'm trying to integrate the meet widget in my site, but after the login and specify the roomID/URI and joining the room, start the connect spinner that never ends or just leave the meeting.

This error appear in the cosnole.
```text

 MEETING 596abe0c-6782-40dd-8852-a7c7b4bd3759 getMeeting() Unable to add media WebexMeetingsError: iceCandidate: Ice gathering never completed at doneGatheringIceCandidate (http://localhost:3001/webex-meeting-widget-starter/static/js/vendors~main.chunk.js:66371:16) at RTCPeerConnection.peerConnection.onicecandidate (http://localhost:3001/webex-meeting-widget-starter/static/js/vendors~main.chunk.js:66396:9) 

```

I also tried with the [demo site](https://webex.github.io/widgets/) but same error!!

if you need more information on my dependency or what i'm dooing, let me know

**Comment by lalli-flores** [comment]
@giospada, please contact Webex developer support team https://developer.webex.com/support so they can help you troubleshoot/replicate the issue.

It would be helpful if you include details such as:
* browser name/version
* OS
* Reproduction steps
* Any logs and/or tracking IDs that you get

From the error message alone, I don't think it is an issue related with bundling, it seems like it could be related to your network. Have you tried running your app on a different network?

**Comment by giospada** [comment]
Thank you for the help, the  `https://developer.webex.com/support` is nice
