### ISSUE TITLE
Space Widget script is messing with site CSS

### ISSUE THREAD

**Issue by OwenVey** [webex/widgets#176]
I am loading the Space Widget via the following script tag:
```html
<script id="webex-widget-script" defer async src="https://code.s4d.io/widget-space/production/bundle.js"></script>
```
There are styles being injected from this script into the `<head>` of my HTML that conflict with a lot of my site. The biggest offenders are where you have selectors with `[class*='md']`. I am using Tailwind in my project which makes heavy use of classes prefixed with `md:` for breakpoint control. The `[class*='md']` selector is selecting all of the elements that have `md` in their class name.

I think a solution for this would be adding a vendor prefix to all of your CSS classes and using that in your selectors.

If you would like a better explanation let me know.

**Comment by lalli-flores** [comment]
@OwenVey, this is the incorrect repository for the Space widget. Space widget lives on https://github.com/webex/react-widgets
Please use https://developer.webex.com/support for troubleshooting help. 

In terms of your query, Space widget uses Webex design system ["Momentum UI"](https://github.com/momentum-design/momentum-ui), and the "md" prefix is already the chosen prefix for momentum design (md) classes
